### ISSUE TITLE
Fix Solr HTTP 503 error

### ISSUE THREAD

**Issue by caioquirino** [caioquirino/docker-cloudera-quickstart#8]
When i open the solr page or Hue Search, the following error is showed:
HTTP Status 503 - Server is shutting down

**Comment by caioquirino** [comment]
More details of the error:

2015-03-18 01:15:29 ERROR SolrCore:119 - null:org.apache.solr.common.SolrException: solr.xml not found in ZooKeeper
        at org.apache.solr.core.ConfigSolr.fromSolrHome(ConfigSolr.java:118)
        at org.apache.solr.core.CoreContainer.<init>(CoreContainer.java:143)
        at org.apache.solr.core.CoreContainer.<init>(CoreContainer.java:133)
        at org.apache.solr.servlet.SolrDispatchFilter.createCoreContainer(SolrDispatchFilter.java:167)
        at org.apache.solr.servlet.SolrDispatchFilter.init(SolrDispatchFilter.java:147)
        at org.apache.catalina.core.ApplicationFilterConfig.getFilter(ApplicationFilterConfig.java:298)
        at org.apache.catalina.core.ApplicationFilterConfig.<init>(ApplicationFilterConfig.java:119)
        at org.apache.catalina.core.StandardContext.filterStart(StandardContext.java:4076)
        at org.apache.catalina.core.StandardContext.start(StandardContext.java:4730)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:799)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:779)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:583)
        at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1079)
        at org.apache.catalina.startup.HostConfig.deployDirectories(HostConfig.java:1002)
        at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:506)
        at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1317)
        at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:324)
        at org.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.java:142)
        at org.apache.catalina.core.ContainerBase.start(ContainerBase.java:1065)
        at org.apache.catalina.core.StandardHost.start(StandardHost.java:822)
        at org.apache.catalina.core.ContainerBase.start(ContainerBase.java:1057)
        at org.apache.catalina.core.StandardEngine.start(StandardEngine.java:463)
        at org.apache.catalina.core.StandardService.start(StandardService.java:525)
        at org.apache.catalina.core.StandardServer.start(StandardServer.java:754)
        at org.apache.catalina.startup.Catalina.start(Catalina.java:595)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:289)
        at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:414)

**Comment by andyburgin** [comment]
Taken a while to suss this, but the solr config file wasn't being copied to the image until after "solrctl init" had run, also zookeeper needs to be running when "solrctl init" is issued so needed "service hbase-master start".

Solr samples now install and run through hue

Created pull request for review

**Comment by caioquirino** [comment]
Hi Andy! Thank you for the collaboration! I'm tested now via Docker Hub and the Cloudera Search is fully working. Thanks! :D
